// adapters.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';

import claude from '../scripts/adapters/claude.mjs';
import cursor from '../scripts/adapters/cursor.mjs';
import codex from '../scripts/adapters/codex.mjs';
import gemini from '../scripts/adapters/gemini.mjs';
import opencode from '../scripts/adapters/opencode.mjs';
import grokBuild from '../scripts/adapters/grok-build.mjs';
import copilot from '../scripts/adapters/copilot.mjs';
import kiro from '../scripts/adapters/kiro.mjs';
import codebuddy from '../scripts/adapters/codebuddy.mjs';
import trae from '../scripts/adapters/trae.mjs';
import vscode from '../scripts/adapters/vscode.mjs';
import zed from '../scripts/adapters/zed.mjs';
import qwen from '../scripts/adapters/qwen.mjs';

const ADAPTERS = [
  claude,
  cursor,
  codex,
  gemini,
  opencode,
  grokBuild,
  copilot,
  kiro,
  codebuddy,
  trae,
  vscode,
  zed,
  qwen,
];

const ctx = {
  projectName: 'sdd_template',
  rulesText: '# Constitution\n\n- Follow the goal.',
};

test('each adapter exposes id, name, and generate()', () => {
  for (const a of ADAPTERS) {
    assert.equal(typeof a.id, 'string');
    assert.equal(typeof a.name, 'string');
    assert.equal(typeof a.generate, 'function');
  }
});

test('each adapter returns at least one { path, content } file', () => {
  for (const a of ADAPTERS) {
    const files = a.generate(ctx);
    assert.ok(Array.isArray(files) && files.length >= 1, `${a.id} returned no files`);
    for (const f of files) {
      assert.equal(typeof f.path, 'string');
      assert.equal(typeof f.content, 'string');
      assert.ok(f.content.length > 0);
    }
  }
});

test('generated markdown adapter files carry the header and managed markers', () => {
  for (const a of ADAPTERS) {
    for (const f of a.generate(ctx)) {
      if (f.path.endsWith('.md') || f.path.endsWith('.mdc')) {
        assert.ok(
          f.content.includes('AUTO-GENERATED by sdd_template'),
          `${f.path} missing header`,
        );
        assert.ok(
          f.content.includes('BEGIN MANAGED AGENT RULES'),
          `${f.path} missing managed marker`,
        );
      }
    }
  }
});

test('claude and gemini emit valid JSON settings', () => {
  const claudeFiles = claude.generate(ctx);
  const settings = claudeFiles.find((f) => f.path === '.claude/settings.json');
  assert.doesNotThrow(() => JSON.parse(settings.content));

  const geminiFiles = gemini.generate(ctx);
  const gset = geminiFiles.find((f) => f.path === '.gemini/settings.json');
  assert.doesNotThrow(() => JSON.parse(gset.content));
});

test('JSON-emitting adapters produce parseable settings', () => {
  const jsonOutputs = [
    [kiro, '.kiro/settings/mcp.json'],
    [vscode, '.vscode/settings.json'],
    [zed, '.zed/settings.json'],
  ];
  for (const [adapter, path] of jsonOutputs) {
    const file = adapter.generate(ctx).find((f) => f.path === path);
    assert.ok(file, `${adapter.id} did not emit ${path}`);
    assert.doesNotThrow(() => JSON.parse(file.content), `${path} is not valid JSON`);
  }
});

test('kiro steering file uses inclusion:auto frontmatter', () => {
  const steering = kiro.generate(ctx).find((f) => f.path.startsWith('.kiro/steering/'));
  assert.ok(steering, 'kiro did not emit a steering file');
  assert.ok(steering.content.startsWith('---\n'), 'steering missing frontmatter');
  assert.ok(steering.content.includes('inclusion: auto'), 'steering missing inclusion:auto');
});

test('adapter ids are unique', () => {
  const ids = ADAPTERS.map((a) => a.id);
  assert.equal(new Set(ids).size, ids.length, 'duplicate adapter id detected');
});
