// adapters.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';

import claude from '../scripts/adapters/claude.mjs';
import cursor from '../scripts/adapters/cursor.mjs';
import codex from '../scripts/adapters/codex.mjs';
import gemini from '../scripts/adapters/gemini.mjs';
import opencode from '../scripts/adapters/opencode.mjs';
import grokBuild from '../scripts/adapters/grok-build.mjs';
import copilot from '../scripts/adapters/copilot.mjs';

const ADAPTERS = [claude, cursor, codex, gemini, opencode, grokBuild, copilot];

const ctx = {
  projectName: 'sdd_template',
  rulesText: '# Constitution\n\n- Follow the goal.',
};

test('each adapter exposes id, name, and generate()', () => {
  for (const a of ADAPTERS) {
    assert.equal(typeof a.id, 'string');
    assert.equal(typeof a.name, 'string');
    assert.equal(typeof a.generate, 'function');
  }
});

test('each adapter returns at least one { path, content } file', () => {
  for (const a of ADAPTERS) {
    const files = a.generate(ctx);
    assert.ok(Array.isArray(files) && files.length >= 1, `${a.id} returned no files`);
    for (const f of files) {
      assert.equal(typeof f.path, 'string');
      assert.equal(typeof f.content, 'string');
      assert.ok(f.content.length > 0);
    }
  }
});

test('generated markdown adapter files carry the header and managed markers', () => {
  for (const a of ADAPTERS) {
    for (const f of a.generate(ctx)) {
      if (f.path.endsWith('.md') || f.path.endsWith('.mdc')) {
        assert.ok(
          f.content.includes('AUTO-GENERATED by sdd_template'),
          `${f.path} missing header`,
        );
        assert.ok(
          f.content.includes('BEGIN MANAGED AGENT RULES'),
          `${f.path} missing managed marker`,
        );
      }
    }
  }
});

test('claude and gemini emit valid JSON settings', () => {
  const claudeFiles = claude.generate(ctx);
  const settings = claudeFiles.find((f) => f.path === '.claude/settings.json');
  assert.doesNotThrow(() => JSON.parse(settings.content));

  const geminiFiles = gemini.generate(ctx);
  const gset = geminiFiles.find((f) => f.path === '.gemini/settings.json');
  assert.doesNotThrow(() => JSON.parse(gset.content));
});
