// source-audit.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';

import { assessSafety, buildAudit } from '../scripts/source-audit.mjs';

test('archived / never-import sources are flagged unsafe', () => {
  const src = {
    id: 'x',
    priority: 'archived',
    tier: 'historical',
    import_policy: 'never-import',
    quarantine: true,
    target: 'external/sources/x',
  };
  const { safe, reasons } = assessSafety(src, { status: 'not-downloaded', license_files: [] });
  assert.equal(safe, false);
  assert.ok(reasons.length > 0);
});

test('quarantined reference-only source is unsafe for auto import', () => {
  const src = {
    id: 'y',
    priority: 'required',
    tier: 'official',
    import_policy: 'reference-only',
    quarantine: true,
    target: 'external/sources/y',
  };
  const { safe } = assessSafety(src, { status: 'downloaded', license_files: ['LICENSE'] });
  assert.equal(safe, false);
});

test('buildAudit includes the auto-generated header and a section per source', () => {
  const manifest = {
    sources: [
      {
        id: 'ecc',
        name: 'ECC',
        url: 'https://example.com/ecc.git',
        target: 'external/sources/ecc',
        priority: 'required',
        tier: 'core',
        import_policy: 'curated-only',
        quarantine: false,
        purpose: 'test',
      },
    ],
  };
  const lock = {
    sources: [{ id: 'ecc', status: 'downloaded', license_files: ['LICENSE'], commit: 'abc123' }],
    failures: [],
  };
  const md = buildAudit(manifest, lock);
  assert.ok(md.includes('AUTO-GENERATED by sdd_template'));
  assert.ok(md.includes('## ecc'));
  assert.ok(md.includes('- Status: downloaded'));
});
