// sync.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';

import { planSync, loadRulesText } from '../scripts/sync.mjs';

test('loadRulesText returns composed rule content', () => {
  const text = loadRulesText();
  assert.ok(text.length > 0);
  assert.ok(text.includes('Constitution'));
});

test('planSync produces all expected outputs', () => {
  const outputs = planSync('sdd_template');
  const paths = outputs.map((o) => o.path);

  const expected = [
    'AGENTS.md',
    'docs/agents.md',
    'CLAUDE.md',
    '.claude/settings.json',
    '.cursor/rules/sdd_template.mdc',
    '.codex/instructions.md',
    'GEMINI.md',
    '.gemini/settings.json',
    '.opencode/instructions.md',
    '.grok/instructions.md',
    '.github/copilot-instructions.md',
  ];
  for (const p of expected) {
    assert.ok(paths.includes(p), `missing planned output: ${p}`);
  }
});

test('every generated markdown output includes the auto-generated header', () => {
  const outputs = planSync('sdd_template');
  for (const out of outputs) {
    if (out.path.endsWith('.md') || out.path.endsWith('.mdc')) {
      assert.ok(
        out.content.includes('AUTO-GENERATED by sdd_template'),
        `missing header in ${out.path}`,
      );
    }
  }
});

test('managed markdown outputs include managed markers', () => {
  const outputs = planSync('sdd_template');
  const agents = outputs.find((o) => o.path === 'AGENTS.md');
  assert.ok(agents.content.includes('<!-- BEGIN MANAGED AGENT RULES -->'));
  assert.ok(agents.content.includes('<!-- END MANAGED AGENT RULES -->'));
});
