// markers.mjs
// Shared constants/helpers for generated, managed agent-config files.

export const AUTO_HEADER = `<!-- AUTO-GENERATED by sdd_template. Do not edit directly.
Source: rules/, skills/, hooks/, mcp-configs/, knowledge/
Run: npm run sync
-->`;

export const BEGIN_MARK = '<!-- BEGIN MANAGED AGENT RULES -->';
export const END_MARK = '<!-- END MANAGED AGENT RULES -->';

/** Wrap generated content in managed markers. */
export function managedBlock(content) {
  return `${BEGIN_MARK}\n${content}\n${END_MARK}`;
}

/** Prepend the auto-generated header to a markdown document. */
export function withHeader(body) {
  return `${AUTO_HEADER}\n\n${body}\n`;
}

/**
 * Replace the content between managed markers in an existing document,
 * preserving any user-written content outside the markers. If markers are
 * absent, the managed block is appended.
 */
export function upsertManaged(existing, content) {
  const block = managedBlock(content);
  if (existing && existing.includes(BEGIN_MARK) && existing.includes(END_MARK)) {
    const before = existing.slice(0, existing.indexOf(BEGIN_MARK));
    const after = existing.slice(existing.indexOf(END_MARK) + END_MARK.length);
    return `${before}${block}${after}`;
  }
  return existing ? `${existing.trimEnd()}\n\n${block}\n` : `${block}\n`;
}

export default { AUTO_HEADER, BEGIN_MARK, END_MARK, managedBlock, withHeader, upsertManaged };
